# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title
#relative_permalinks: true

# Setup
title:            Monjur Mourshed
tagline:          'Smart and resilient urban environments'
description:      'Smart and resilient urban environments, energy and buildings, and climate change adaptation.'
url:              http://m.mourshed.org
baseurl:          /

author:
  name:           'Monjur Mourshed'
  url:            https://twitter.com/mmourshed

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mmourshed

# Gems
gems: [jekyll-paginate, jekyll-gist]

# Social media
twitter_username:     mmourshed
github_username:      mmourshed
linkedin_username:    mmourshed
google_plus_username: 112684616029246000911
facebook_username:    
dribbble_username:
#Facebook Sharing
facebook_app_id:      1712485889075298